name: build and deploy jhipster application
on: [push, pull_request]
jobs:
  publish-docker:
    name: Publish Docker
    if: contains(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/')
    concurrency: # Ensures only one deploy job runs at a time
      group: deployment
    #runs-on: self-hosted means you need to set up self-hosted runners to run this job
    #see https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    services:
      docker:
        image: docker:dind
        options: >-
          --privileged
          --env DOCKER_TLS_CERTDIR=
        ports:
          - 2375:2375
    env:
      DOCKER_HOST: 'tcp://127.0.0.1:2375'
      DOCKER_DRIVER: overlay2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for Docker Daemon
        run: |
          for i in {1..10}; do
            if docker info; then
              break
            fi
            echo "Waiting for Docker Daemon..."
            sleep 3
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-v1-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-v1-

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Build and push Docker image to ghcr
        run: |
          echo "pushing ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}"
          ./mvnw -ntp clean compile jib:build -DskipTests -Pprod \
            -Djib.to.auth.username=${{ github.actor }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }} \
            -Djib.to.image=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }} \
            -Djib.to.tags=latest \
            -Dmaven.repo.local=$MAVEN_USER_HOME
        env:
          MAVEN_USER_HOME: ~/.m2/repository

  deploy-dev:
    name: deploy development app via ssh
    runs-on: self-hosted
    needs: publish-docker
    #if: success() means previous stages must pass;
    if: success() && ( contains(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/') )
    concurrency: # Ensures only one deploy job runs at a time
      group: deployment

    env:
      RSA_PRIVATE_KEY: ${{secrets.RSA_PRIVATE_KEY}}
      URL: '${{ github.event.repository.name }}.bham.team' # URL as per project name
      DEVURL: '${{ github.event.repository.name }}.dev.bham.team' # URL as per project name
      ACME: 'https://acme-v02.api.letsencrypt.org/directory'
      ACME_STAGING: 'https://acme-staging-v02.api.letsencrypt.org/directory'
      CI_REGISTRY_USER: ${{ github.actor }} # GitHub username for authentication
      CI_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }} # GitHub token to authenticate to GHCR
      CI_REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.repository }} # GHCR image URL
      CI_REGISTRY: ghcr.io # GHCR registry URL

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up SSH key for connection
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$RSA_PRIVATE_KEY" > ~/.ssh/id_rsa  # Add private key (stored in GitHub Secrets)
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)  # Start SSH agent
          ssh-add ~/.ssh/id_rsa  # Add the private key to the agent

      # Add known hosts to prevent SSH from asking to verify the host
      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_IP }} >> ~/.ssh/known_hosts

      # Save CI pipeline variables ready for transfer
      - name: Save CI variables for transfer
        run: |
          echo CI_REGISTRY_USER=${{ env.CI_REGISTRY_USER }} \
               CI_REGISTRY_PASSWORD=${{ env.CI_REGISTRY_PASSWORD }} \
               CI_REGISTRY_IMAGE=${{ env.CI_REGISTRY_IMAGE }} \
               CI_COMMIT_TAG=${{ github.sha }} \
               CI_REGISTRY=${{ env.CI_REGISTRY }} \
               ACME=${{ env.ACME_STAGING }} \
               DEVURL=${{ env.DEVURL }} \
               URL=${{ env.URL }} \
               DEPLOY_IP=${{ secrets.DEPLOY_IP }} \
               EMAIL=${{ github.event.head_commit.author.email }} > src/main/docker/.env

      # SSH into the VM and ensure Docker is installed, delete previous folder
      - name: Install Docker and prepare the server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "
            rm -rf ~/team-project || true
            which docker || sh team-project/install-docker.sh
          "

      # Transfer the necessary files to the VM
      - name: Transfer files to the server
        run: |
          scp -o StrictHostKeyChecking=no -r src/main/docker/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }}:~/team-project

      # Run app installation on the VM
      - name: Install app on the server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "sh team-project/install-app.sh"

      # Deploy the app and clean up Docker system
      - name: Deploy and clean Docker
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "
            docker compose -f ~/team-project/dev.yml up -d
            docker system prune --force --filter 'until=24h'
          "

  deploy-prod:
    name: deploy production version via ssh
    runs-on: self-hosted
    needs: deploy-dev
    if: success() && startsWith(github.ref, 'refs/tags/')

    concurrency: # Ensures only one deploy job runs at a time
      group: deployment

    env:
      RSA_PRIVATE_KEY: ${{secrets.RSA_PRIVATE_KEY}}

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up SSH key for connection
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$RSA_PRIVATE_KEY" > ~/.ssh/id_rsa  # Add private key (stored in GitHub Secrets)
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)  # Start SSH agent
          ssh-add ~/.ssh/id_rsa  # Add the private key to the agent

      # Add known hosts to prevent  from asking to verify the host
      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_IP }} >> ~/.ssh/known_hosts

      # Deploy the production application using Docker Compose
      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "
            docker compose -f ~/team-project/prd.yml up -d
            docker system prune --force --filter 'until=24h'
          "
